apiVersion: 1

datasources:
  - name: Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Logs
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
